services:
  - type: web
    name: kartavya-backend-server
    runtime: docker
    rootDir: backend-server
    plan: free
    region: oregon
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyADjvknSiVO5hSfsevGj4noi5VKKVOu0H0
      - key: SARVAM_API_KEY
        value: sk_xxivlmol_9VkYQj9XsD0vUjQDQYHfinYL
      - key: STORAGE_DIR
        value: /app/data/uploads
