services:
  - type: web
    name: kartavya-backend-server
    runtime: docker
    rootDir: backend-server
    plan: free
    region: oregon
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SARVAM_API_KEY
        sync: false
      - key: MEDIA_STORAGE_PROVIDER
        value: firebase
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: STORAGE_DIR
        value: /app/data/uploads
