package com.example.kartavya.data

import android.util.Log
import com.example.kartavya.model.CivicIssue
import com.example.kartavya.model.IssueStatus
import com.google.firebase.firestore.FieldValue
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.ListenerRegistration
import com.google.firebase.firestore.Query
import kotlinx.coroutines.tasks.await

/**
 * Manages civic issue documents in Firestore at issues/{issueId}.
 *
 * Every issue carries the creator's Firebase UID in [CivicIssue.userId].
 * Security rules enforce userId == request.auth.uid on creation and
 * prevent userId changes on update.
 */
object IssueRepository {

    private const val TAG = "IssueRepository"
    private const val COLLECTION = "issues"

    private val db: FirebaseFirestore by lazy { FirebaseFirestore.getInstance() }

    /**
     * Create a new civic issue document.
     *
     * The document ID is auto-generated by Firestore.
     * Server timestamps are used for createdAt and updatedAt.
     *
     * @return The generated document ID.
     */
    suspend fun createIssue(issue: CivicIssue): Result<String> {
        return try {
            require(issue.userId.isNotBlank()) { "userId must not be blank" }

            val data = hashMapOf(
                "userId" to issue.userId,
                "reporterName" to issue.reporterName,
                "title" to issue.title,
                "description" to issue.description,
                "category" to issue.category,
                "imageUrls" to issue.imageUrls,
                "audioUrl" to issue.audioUrl,
                "latitude" to issue.latitude,
                "longitude" to issue.longitude,
                "address" to issue.address,
                "status" to IssueStatus.REPORTED.name,
                "routingTo" to issue.routingTo,
                "priority" to issue.priority,
                "upvotes" to issue.upvotes,
                "upvoteCount" to issue.upvotes,
                "upvotedBy" to issue.upvotedBy,
                "createdAt" to FieldValue.serverTimestamp(),
                "updatedAt" to FieldValue.serverTimestamp()
            )

            val docRef = db.collection(COLLECTION).add(data).await()
            Log.i(TAG, "Created issue ${docRef.id} by user ${issue.userId}")
            Result.success(docRef.id)
        } catch (e: Exception) {
            Log.e(TAG, "Failed to create issue", e)
            Result.failure(e)
        }
    }

    /**
     * Observe recent civic issues in real-time, ordered by creation time.
     *
     * @return [ListenerRegistration] that the caller must remove on dispose.
     */
    fun observeRecentIssues(
        limit: Long = 50,
        onUpdate: (List<CivicIssue>) -> Unit
    ): ListenerRegistration {
        return db.collection(COLLECTION)
            .limit(limit)
            .addSnapshotListener { snapshot, error ->
                if (error != null) {
                    Log.w(TAG, "Issues listen error", error)
                    onUpdate(emptyList())
                    return@addSnapshotListener
                }
                if (snapshot != null && !snapshot.isEmpty) {
                    val list = snapshot.documents.mapNotNull { doc ->
                        try {
                            CivicIssue.fromDocument(doc)
                        } catch (e: Exception) {
                            Log.e(TAG, "Failed to parse issue doc ${doc.id}", e)
                            null
                        }
                    }.sortedByDescending { it.createdAt?.seconds ?: it.updatedAt?.seconds ?: 0L }
                    onUpdate(list)
                } else {
                    onUpdate(emptyList())
                }
            }
    }

    /**
     * Get issues created by a specific user.
     */
    suspend fun getUserIssues(uid: String): List<CivicIssue> {
        return try {
            val snapshot = db.collection(COLLECTION)
                .whereEqualTo("userId", uid)
                .get()
                .await()
            snapshot.documents.mapNotNull { doc ->
                try {
                    CivicIssue.fromDocument(doc)
                } catch (e: Exception) {
                    null
                }
            }.sortedByDescending { it.createdAt?.seconds ?: it.updatedAt?.seconds ?: 0L }
        } catch (e: Exception) {
            Log.w(TAG, "Failed to get user issues", e)
            emptyList()
        }
    }

    /**
     * Observe issues created by a specific user in real-time.
     */
    fun observeUserIssues(
        uid: String,
        onUpdate: (List<CivicIssue>) -> Unit
    ): ListenerRegistration? {
        if (uid.isBlank()) {
            onUpdate(emptyList())
            return null
        }
        return db.collection(COLLECTION)
            .whereEqualTo("userId", uid)
            .addSnapshotListener { snapshot, error ->
                if (error != null) {
                    Log.w(TAG, "User issues listen error", error)
                    onUpdate(emptyList())
                    return@addSnapshotListener
                }
                if (snapshot != null && !snapshot.isEmpty) {
                    val list = snapshot.documents.mapNotNull { doc ->
                        try {
                            CivicIssue.fromDocument(doc)
                        } catch (e: Exception) {
                            Log.e(TAG, "Failed to parse user issue doc ${doc.id}", e)
                            null
                        }
                    }.sortedByDescending { it.createdAt?.seconds ?: it.updatedAt?.seconds ?: 0L }
                    onUpdate(list)
                } else {
                    onUpdate(emptyList())
                }
            }
    }

    /**
     * Update an issue's status. Designed for future admin functionality.
     */
    suspend fun updateStatus(issueId: String, newStatus: IssueStatus): Result<Unit> {
        return try {
            db.collection(COLLECTION).document(issueId).update(
                mapOf(
                    "status" to newStatus.name,
                    "updatedAt" to FieldValue.serverTimestamp()
                )
            ).await()
            Result.success(Unit)
        } catch (e: Exception) {
            Log.e(TAG, "Failed to update issue status", e)
            Result.failure(e)
        }
    }

    /**
     * Toggle upvote for a civic issue directly in Firebase Firestore.
     * Synchronizes in real-time across all user accounts.
     */
    suspend fun toggleUpvote(issueId: String, uid: String, fallbackIssue: CivicIssue? = null): Result<Unit> {
        return try {
            val effectiveUid = uid.ifBlank { "demo_user" }
            val cleanIssueId = issueId.ifBlank { fallbackIssue?.issueId ?: "demo_issue" }
            val docRef = db.collection(COLLECTION).document(cleanIssueId)

            db.runTransaction { transaction ->
                val snapshot = transaction.get(docRef)
                if (snapshot.exists()) {
                    val upvotedBy = (snapshot.get("upvotedBy") as? List<*>)?.mapNotNull { it?.toString() } ?: emptyList()
                    val hasUpvoted = upvotedBy.contains(effectiveUid)

                    val updates = mutableMapOf<String, Any>()
                    if (hasUpvoted) {
                        updates["upvotedBy"] = FieldValue.arrayRemove(effectiveUid)
                        updates["upvotes"] = FieldValue.increment(-1)
                        updates["upvoteCount"] = FieldValue.increment(-1)
                    } else {
                        updates["upvotedBy"] = FieldValue.arrayUnion(effectiveUid)
                        updates["upvotes"] = FieldValue.increment(1)
                        updates["upvoteCount"] = FieldValue.increment(1)
                    }
                    updates["updatedAt"] = FieldValue.serverTimestamp()
                    transaction.update(docRef, updates)
                } else if (fallbackIssue != null) {
                    // Create issue doc in Firestore so upvote syncs live for all users
                    val initialUpvotes = (fallbackIssue.upvotes + 1).coerceAtLeast(1)
                    val newDoc = hashMapOf(
                        "userId" to fallbackIssue.userId.ifBlank { effectiveUid },
                        "reporterName" to fallbackIssue.reporterName.ifBlank { "Citizen" },
                        "title" to fallbackIssue.title,
                        "description" to fallbackIssue.description,
                        "category" to fallbackIssue.category,
                        "imageUrls" to fallbackIssue.imageUrls,
                        "status" to fallbackIssue.status,
                        "address" to fallbackIssue.address,
                        "priority" to fallbackIssue.priority,
                        "routingTo" to fallbackIssue.routingTo,
                        "upvotes" to initialUpvotes,
                        "upvoteCount" to initialUpvotes,
                        "upvotedBy" to listOf(effectiveUid),
                        "createdAt" to FieldValue.serverTimestamp(),
                        "updatedAt" to FieldValue.serverTimestamp()
                    )
                    transaction.set(docRef, newDoc)
                }
            }.await()
            Log.i(TAG, "Successfully toggled upvote in Firebase for issue $cleanIssueId by $effectiveUid")
            Result.success(Unit)
        } catch (e: Exception) {
            Log.e(TAG, "Failed to toggle upvote for $issueId", e)
            Result.failure(e)
        }
    }
}
